export const SELECT_SOURCE = 'SELECT_SOURCE';
export const INVALIDATE_SOURCE = 'INVALIDATE_SOURCE';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SELECT_SOURCES = 'SELECT_SOURCES';
export const SELECT_ALL = 'SELECT_ALL';
export const UNSELECT_ALL = 'UNSELECT_ALL';